name: PR Checks

# 触发条件：当有PR提交到main分支时运行--》改为手动触发
on:
workflow_dispatch

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest safety
          pip install -r requirements.txt

      - name: 代码风格检查（flake8）
        run: flake8 src/ --max-line-length=120

      - name: 单元测试（pytest）
        run: pytest tests/ --cov=src/

      - name: 依赖安全扫描（safety）
        run: safety check --full-report
